### ISSUE TITLE
Prebuilt Wheels for Python 3.9

### ISSUE THREAD

**Issue by FredHappyface** [aio-libs/multidict#534]
**Is your feature request related to a problem? Please describe.**
When installing a project that uses this as a dependency, the end user is required to install visual c++ >=14 on Windows.

**Describe the solution you'd like**
Would it be possible to create prebuilt wheels for py 3.9 as has been done for previous versions?

**Describe alternatives you've considered**
It would be nice if Windows had these tools installed by default as is the case in many Linux distros... 

**Additional context**
Thanks very much for your time :D

**Comment by webknjaz** [comment]
Hi, I guess if somebody sends a PR updating the CI/CD configuration, we could do something about it :)

**Comment by FredHappyface** [comment]
I'd be interested in taking a look at this but do you mind if I run a few things here?

So is it as simple as adding the following to azure for Windows and Mac?

I'm assuming there's quite a bit more complexity to manylinux1?

add to deploy.yml
```
Win py39 x64:
          python.version: '3.9'
          python.architecture: 'x64'
          image: 'windows-latest'
Win py39 x86:
          python.version: '3.9'
          python.architecture: 'x86'
          image: 'windows-latest'
Mac py39:
          python.version: '3.9'
          image: 'macos-latest'
          python.architecture: 'x64'
```


add to stage-test
```
Py39-C-Win:
          python.version: '3.9'
          no_extensions: ''
          image: 'windows-latest'
 Py39-C-Mac:
          python.version: '3.9'
          no_extensions: ''
          image: 'macos-latest'
```
